### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by wenqingchu** [zhanghang1989/PyTorch-Encoding#69] opened 2018-06-12 00:15 UTC
Hi,
 I run the cmd "python test.py --dataset PContext --model-zoo Encnet_ResNet50_PContext --eval". The PixAcc is 0.7784 and the mIoU is 0.4827. Is this ok? I use the latest version of your code. Thanks for your attention.

**Comment by lxtGH** [comment] 2018-06-12 12:45
Hi @zhanghang1989  How to reproduce the results as your paper. 
I tried to train ADE, 150 epoches with your default settings, but I only got 0.7866, mIoU: 0.3878 
In your paper this is 79.74 / 41.11 , did you use multi-scale test?? I set batchsize 16,with 4GPUs

**Comment by zhanghang1989** [comment] 2018-06-12 14:20
I will release the training detail on ADE20K dataset soon.

**Comment by lxtGH** [comment] 2018-06-13 15:03
@zhanghang1989 also the pascal voc/aug acc is still far away from your paper. pascal context near, but still a little away from your paper.

**Comment by zhanghang1989** [comment] 2018-06-13 15:13
Hi @lxtGH , the little gap on pascal context is because of the base model. You will see an updated EncNet and base model soon in next release.  The ADE training and pre-trained model will be available as well. The Pascal VOC training, please wait later vision.

**Comment by lxtGH** [comment] 2018-06-14 13:08
Hi !@zhanghang1989 , again thanks for reply. I have the following questions.
1, In your code, why you use tuple as the output to match your custom loss function. 
2, Also, I didn't find  GPU **memory improvement** using your data parallel and the master memory always higher the slave.
3, to use your Syn-bn correctly, **Must I use the your custom data parallel and cirition.**

**Comment by zhanghang1989** [comment] 2018-06-14 19:52
Hi, just an update the new version will be released today.
1. This tuple thing handles the condition of multiple outputs from the network.
2. The GPU in-balance currently is because PyTorch issue during the evaluation, the easiest way to avoid it is to disable the validation during the training by setting `--no-val`
3. You can use standard `torch.nn.DataParallel` and 'patch' it by using https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/parallel.py#L225

**Closed** 2018-06-15 04:48 UTC

**Comment by lxtGH** [comment] 2018-06-18 08:03
Hi ! @zhanghang1989 
I reproduced the nearly all experiments using your code. However, except for the pascal context(**a little gap**).
Other results are **much gap** between default setting and your paper.
When you train the voc, you use the COCO dataset for pretraining? and then finetune？
Also I want to know about training details about ADE-20k data set.

**Comment by zhanghang1989** [comment] 2018-06-18 12:34
Pretrain on COCO => fine tuning on Pascal Aug => finetuning on Pascal VOC.

**Comment by lxtGH** [comment] 2018-06-21 10:33
@zhanghang1989 I reinstall this repo but got this error
ImportError: /home/xiangtai/anaconda3/lib/python3.6/site-packages/encoding/lib/cpu/enclib_cpu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by zhanghang1989** [comment] 2018-06-26 16:40
Hi @lxtGH, just wanted to follow up. the training example of ADE20K is also released. Let me know if you still have problem reproducing the experiments.

**Comment by lxtGH** [comment] 2018-06-26 17:32
Hi! Thanks for reply. @zhanghang1989 So the main difference is the **crop size, base size** in the code, and 20 more epochs?  Actually I trained the model **180** epochs.
*base_size=520, crop_size=480 -> base_size=576, crop_size=608.* How did you find this size?

**Comment by zhanghang1989** [comment] 2018-06-26 18:12
Larger crop size often leads to better performance, but consumes larger memory. It is a kind of trade-off. We typically use large size when reporting results on benchmarks.

**Comment by XRSWATER** [comment] 2019-05-01 12:44
> Larger crop size often leads to better performance, but consumes larger memory. It is a kind of trade-off. We typically use large size when reporting results on benchmarks. The sizes are empirically chosen.

Hi, after resetting the codes I still have the error:
ImportError: /home/PyTorch-Encoding/experiments/segmentation/encoding/lib/cpu/enclib_cpu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Would you mind giving me some suggestions? Why I have such an error？

**Comment by ygjwd12345** [comment] 2020-09-28 06:36
@XRSWATER @zhanghang1989 For the new version, the problem also exists.
Traceback (most recent call last):
  File "./experiments/segmentation/train.py", line 18, in <module>
    import encoding.utils as utils
  File "/data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/functions/encoding.py", line 15, in <module>
    from encoding.lib import cpu
  File "/data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/lib/__init__.py", line 14, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/gyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 921, in load
    is_python_module)
  File "/home/gyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1120, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/gyang/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1445, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/home/gyang/anaconda3/envs/pytorch/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/gyang/anaconda3/envs/pytorch/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/lib/cpu/enclib_cpu.so: undefined symbol: _Z16CONV_RECTIFY_CPURN2at6TensorERKS0_N3c108ArrayRefIlEES6_S6_S6_b
