### ISSUE TITLE
Fail to install in Ubuntu 14.04

### ISSUE THREAD

**Issue by SoonminHwang** [zhanghang1989/PyTorch-Encoding#17] opened 2017-12-14 13:58 UTC
Hi.
Thanks for your effort.

I fail to install your library on my machine (Ubuntu 14.04, CUDA 8.0, python3 with anaconda).

````
$ python setup.py install
-- The C compiler identification is GNU 4.9.4
-- The CXX compiler identification is GNU 4.9.4
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/gcc
-- Check for working CXX compiler: /usr/bin/gcc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- TORCH_BUILD_DIR: /home/rcvlab/anaconda3/lib/python3.5/site-packages/torch/lib
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.5")
-- Autodetected CUDA architecture(s): 6.1 6.1
-- Torch_INSTALL_INCLUDE:/home/rcvlab/anaconda3/lib/python3.5/site-packages/torch/lib/include/home/rcvlab/anaconda3/lib/python3.5/site-packages/torch/lib/include/TH/home/rcvlab/anaconda3/lib/python3.5/site-packages/torch/lib/include/THC
-- Configuring done
-- Generating done
-- Build files have been written to: /media/rcvlab/soonmin2017/pytorch.segmentation/semantic/external/PyTorch-Encoding/encoding/lib
[100%] Building NVCC (Device) object CMakeFiles/ENCODING.dir/kernel/./ENCODING_generated_thc_encoding.cu.o
CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCStorage.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THCStorageCopy.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensor.h

CMake Warning at /usr/share/cmake-2.8/Modules/FindCUDA/make2cmake.cmake:66 (message):
   Removing non-existent dependency file: generic/THTensorCopy.h
...

/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stddef.h(432): error: identifier "nullptr" is undefined
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/stddef.h(432): error: expected a ";"
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h(192): error: expected a ";"
/usr/include/c++/4.9/exception(63): error: expected a ";"
````

And finally, 

````
/usr/include/c++/4.9/cmath(240): error: inline specifier allowed on function declarations only

/usr/include/c++/4.9/cmath(240): error: variable "std::constexpr" has already been defined

/usr/include/c++/4.9/cmath(240): error: expected a ";"

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_0000331f_00000000-7_thc_encoding.cpp1.ii".
Compilation terminated.
CMake Error at ENCODING_generated_thc_encoding.cu.o.cmake:264 (message):
  Error generating file
  /media/rcvlab/soonmin2017/pytorch.segmentation/semantic/external/PyTorch-Encoding/encoding/lib/CMakeFiles/ENCODING.dir/kernel/./ENCODING_generated_thc_encoding.cu.o


make[2]: *** [CMakeFiles/ENCODING.dir/kernel/./ENCODING_generated_thc_encoding.cu.o] Error 1
make[1]: *** [CMakeFiles/ENCODING.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    'install': install,
  File "/home/rcvlab/anaconda3/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/rcvlab/anaconda3/lib/python3.5/site-packages/setuptools/dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "/home/rcvlab/anaconda3/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/home/rcvlab/anaconda3/lib/python3.5/site-packages/setuptools/dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/rcvlab/anaconda3/lib/python3.5/site-packages/cffi/setuptools_ext.py", line 188, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/rcvlab/anaconda3/lib/python3.5/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/rcvlab/anaconda3/lib/python3.5/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "/media/rcvlab/soonmin2017/pytorch.segmentation/semantic/external/PyTorch-Encoding/build.py", line 36, in <module>
    subprocess.check_call(build_all_cmd, env=dict(os.environ))
  File "/home/rcvlab/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'encoding/make.sh']' returned non-zero exit status 2
````

I guess it's a gcc compiler issue, but I'm not sure.
Could you give me a hint for it?

**Comment by zhanghang1989** [comment] 2017-12-25 00:34
Hi, I don't have a ubuntu machine at hand now for reproducing the error. I will follow up this issue next month.

**Comment by liruilong940607** [comment] 2018-01-15 18:16
I also got this issue, but I seem to find a solution.

change line 5 in  `encoding/make.sh` 
from
`  cmake  ..`
to
`  cmake -DCUDA_NVCC_FLAGS='-std=c++11' ..`
works for me.

**Comment by cbelth** [comment] 2018-02-27 16:06
The above solution doesn't work for me.

**Comment by zhanghang1989** [comment] 2018-03-16 21:03
I could not reproduce the above error on my machine. Please try
```
CFLAGS="-std=c99" python setup.py install
```

**Comment by Roll920** [comment] 2018-03-21 15:09
Hi @cbelth, I got the same issue and I solve it as follows,
1. change line 5 in encoding/make.sh to `cmake -DCUDA_NVCC_FLAGS='-std=c++11' ..` as suggested by @liruilong940607 
2. Then the error become to `ImportError: No module named 'tqdm'` . I solve it using `pip install tqdm`

It works for me, my machine environment is `Ubuntu 14.04, cuda 8.0, python 3.6 with Anaconda3 `.

**Comment by zhanghang1989** [comment] 2018-03-21 16:43
Thanks for the efforts and comments! This has been addressed in PR https://github.com/zhanghang1989/PyTorch-Encoding/pull/27 . Feel free to reopen it if still getting the trouble.

**Closed by zhanghang1989** 2018-03-21 16:43 UTC
Labels: bug, mid priority, question
