### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run_slave'

### ISSUE THREAD

**Issue by hfut-fan** [zhanghang1989/PyTorch-Encoding#75] opened 2018-06-21 13:25 UTC
Hi ZHang:

## segmentation

when i train segmentation model, 

```
CUDA_VISIBLE_DEVICES=0  python train.py --dataset pcontext --model encnet --aux --se-loss
```

i face an error:

```
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 80
  0%|                                                                                                                                         | 0/1249 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0003,                 previous best = 0.0000
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    trainer.training(epoch)
  File "train.py", line 105, in training
    outputs = self.model(image)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/models/encnet.py", line 32, in forward
    features = self.base_forward(x)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/models/base.py", line 51, in base_forward
    x = self.pretrained.bn1(x)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 57, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

```

my environment:

-  Quick Demo has been done (success)

- version
```
>>> torch.__version__
'0.5.0a0+32bc28d'
```
- **only one nvidia card : 1080(8G)**

-----------------------------------------------------

## recognition

when i run recognition demo, i

```
python main.py --dataset cifar10 --model encnetdrop --widen 8 --ncodes 32 --resume model/encnet_cifar.pth.tar --eval

```

 also face an error:

```
    (9): View()
    (10): Linear(in_features=512, out_features=10, bias=True)
  )
)
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    main()
  File "main.py", line 56, in main
    Dataloader = dataset.Dataloader
AttributeError: module 'dataset.cifar10' has no attribute 'Dataloader'

```

my environment:

- torchvision:

```
>>> import torchvision
>>> torchvision.__version__
'0.2.1'

```

 Can you help me with this problem? Thank you ~

**Comment by zhanghang1989** [comment] 2018-06-28 18:44
This should have been fixed in recent PR. Let me know if you still have the problem

**Comment by hfut-fan** [comment] 2018-06-29 11:06
thank you  for your response. 
recognition issue has been solved,  **but segmentation issue still remained.**


ps:
segmentation demo has been  running successfully. 

but when i run below command:
```
CUDA_VISIBLE_DEVICES=0  python train.py --dataset pcontext --model Encnet --aux --se-loss

```

still has  issue:

```
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 80
  0%|                                                                                       | 0/1249 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0003,                 previous best = 0.0000
Traceback (most recent call last):
  File "train.py", line 178, in <module>
    trainer.training(epoch)
  File "train.py", line 108, in training
    outputs = self.model(image)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/models/encnet.py", line 32, in forward
    features = self.base_forward(x)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/models/base.py", line 54, in base_forward
    x = self.pretrained.bn1(x)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 57, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'
```

**i have only one GTX card, is this issue related to GTX card?**

**Comment by youansheng** [comment] 2018-07-04 07:19
@zhanghang1989 Does syncbn support single gpu case now?

**Comment by zhanghang1989** [comment] 2018-07-05 17:12
Hi @youansheng , why synchronizing a single gpu? Please use standard BN instead.

**Comment by Gjiangtao** [comment] 2018-08-20 17:55
我遇到了同样的问题，我只有一张单卡1060 3g，当我运行命令`CUDA_VISIBLE_DEVICES=0 python train.py --dataset pcontext --model encnet --aux --se-loss`，报错

> Traceback (most recent call last):
  File "/home/gjt/code/PyTorch-Encoding/experiments/segmentation/train.py", line 178, in <module>
    trainer.training(epoch)
  File "/home/gjt/code/PyTorch-Encoding/experiments/segmentation/train.py", line 108, in training
    outputs = self.model(image)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/models/encnet.py", line 32, in forward
    features = self.base_forward(x)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/models/base.py", line 54, in base_forward
    x = self.pretrained.bn1(x)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 57, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

请问怎么解决这个问题呢？

**Comment by wulei2018** [comment] 2018-10-05 07:06
I meet the same problem,can it be solved now?

**Comment by wulei2018** [comment] 2018-10-05 07:33
> I see. The training requires batch size of 16 to reproduce the performance. The code hasn’t considered single gpu case. I will see if it can be fixed easily.

Can it be fixed now?

**Comment by zhanghang1989** [comment] 2018-10-05 20:59
This code repo does not consider single gpu case. It provides the implementation reproducing the state-of-the-art results in the paper. A single gpu won't be able to do that, because of the limited batch size

**Comment by zhanghang1989** [comment] 2018-10-05 20:59
There is no need to use syncBN for single gpu. Please use the standard BN.

**Comment by wulei2018** [comment] 2018-10-06 06:16
Can you give a detail about how to use standard BN in your code repo？or Do you have code pro for single gpu？Thank u very much.
@zhanghang1989

**Comment by zhanghang1989** [comment] 2018-10-08 17:27
@wulei2018 sure. Simply set `norm_layer=torch.nn.BatchNorm2d` in https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/experiments/segmentation/train.py#L54

**Comment by lfdeep** [comment] 2018-11-29 11:06
> Can you give a detail about how to use standard BN in your code repo？or Do you have code pro for single gpu？Thank u very much.
> @zhanghang1989

I have encountered the same problem, and I only have one gpu. Have you solved this problem? I modified it to norm_layer=torch.nn.BatchNorm2d, but I still have this error.

**Comment by yiqigo0215** [comment] 2018-12-14 08:41
@zhanghang1989 I have encountered the same problem, and I only have one gpu. Have you solved this problem? I modified it to norm_layer=torch.nn.BatchNorm2d, but I still have this error. Thanks

**Comment by lfdeep** [comment] 2018-12-15 09:58
> @zhanghang1989 I have encountered the same problem, and I only have one gpu. Have you solved this problem? I modified it to norm_layer=torch.nn.BatchNorm2d, but I still have this error. Thanks

i have solved this problem!

**Closed** 2018-12-17 22:19 UTC

**Comment by JANGSOONMYUN** [comment] 2020-01-06 13:12
> > @zhanghang1989 I have encountered the same problem, and I only have one gpu. Have you solved this problem? I modified it to norm_layer=torch.nn.BatchNorm2d, but I still have this error. Thanks
> 
> i have solved this problem!

Can you explain how you fixed it?
