### ISSUE TITLE
No module named cpp_extension

### ISSUE THREAD

**Issue by TensorDL** [zhanghang1989/PyTorch-Encoding#67] opened 2018-06-09 01:28 UTC
Hi, I got the error named No module named cpp_extension (from torch.utils.cpp_extension import load) when I run the quick demo http://hangzh.com/PyTorch-Encoding/experiments/segmentation.html#install-package. The version of python and torch are 2.7 and 0.3.1 respectively. How can I handle it?

**Comment by zhanghang1989** [comment] 2018-06-09 18:18
0.3.1 is way too old. Please install PyTorch master branch > 0.5.0

**Comment by Thinker024** [comment] 2018-06-13 13:59
pytorch最新的master branch 是没到0.5.0吧，刚git clone下来只到0.4.0

**Comment by Thinker024** [comment] 2018-06-13 14:38
请问如何install PyTorch master branch > 0.5.0

**Comment by TensorDL** [comment] 2018-06-19 07:53
In your paper, the sentence ''The ground truth labels for SE-loss are generated by “unique” operation finding the categories presented in the given ground-truth segmentation mask.'' means that every input image has multiple labels. As far as I know, the binary cross entroy loss can handle binary class or multi-class task rather than multi-labels.

**Comment by TensorDL** [comment] 2018-06-20 00:58
Multiclass classification means a classification task with more than two classes; e.g., classify a set of images of fruits which may be oranges, apples, or pears. Multiclass classification makes the assumption that each sample is assigned to one and only one label: a fruit can be either an apple or a pear but not both at the same time.  
Multilabel classification assigns to each sample a set of target labels. This can be thought as predicting properties of a data-point that are not mutually exclusive, such as topics that are relevant for a document. A text might be about any of religion, politics, finance or education at the same time or none of these.
I note that the  NN has sigmoid activation. I hold the question that, in your case, the input image has multiple labels or one.

**Comment by zhanghang1989** [comment] 2018-06-20 01:27
The presence of the object categories is indeed a multi-label task. Each category is predicted independently using a binary prediction. I hope it can address your concern.

**Comment by zhanghang1989** [comment] 2018-06-20 01:32
Please refer to the docs for binary cross entropy loss

**Comment by TensorDL** [comment] 2018-06-20 03:48
''Each category is predicted independently using a binary prediction. '' means in this epoch the label of the input image is building (figure 2 in paper), and in next epoch the label of the same input image is car?

**Comment by zhanghang1989** [comment] 2018-06-20 04:42
Each category is a binary classification problem. For 150 categories, there 150 individual binary classification problem. I hope this explanation  is clear enough. If you still have difficulties, feel free to ask questions in Chinese.

**Comment by TensorDL** [comment] 2018-06-20 07:31
Thank you for your patience.  Your explanation is clear. The binary cross entropy loss can handle the multi-label classification task. Its target is something like [1,0,0,1,0...]. Sigmoid, unlike softmax don't give probability distribution around NCLASS as output, but independent probabilities.

**Comment by zhanghang1989** [comment] 2018-06-20 13:23
You’re welcome. That is correct.

**Comment by TensorDL** [comment] 2018-06-24 02:03
I'm sorry for disturbing you again. I shouldn't ask you the question about installation PyTorch from source here, but I can't handle error I got. Can you help me to solve it?

Here is the system info
PyTorch or Caffe2: PyTorch
How you installed PyTorch (conda, pip, source): source
Build command you used (if compiling from source):python setup.py install
OS:ubuntu14.04
PyTorch version:master
Python version:3.6
CUDA/cuDNN version:8.0
GPU models and configuration:GTX1080
GCC version (if compiling from source):4.9.4
CMake version:3.7.2
############################
Issue description: 
python setup.py install
 
running install
running build_deps

USE_CUDA=0
USE_ROCM=0
USE_NNPACK=0
......

-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "7.0")
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;6.1+PTX
-- Set NVCC_GENCODE for building NCCL: -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61
-- Configuring done
-- Generating done
-- Build files have been written to: /media/hh/pytorch_dir/pytorch/third_party/build/nccl

make install
Scanning dependencies of target nccl
[100%] Generating lib/libnccl.so
Grabbing src/nccl.h > /media/hh/pytorch_dir/pytorch/third_party/build/nccl/include/nccl.h
Compiling src/libwrap.cu > /media/hh/pytorch_dir/pytorch/third_party/build/nccl/obj/libwrap.o
nvcc fatal : redefinition of keyword 'code'
make[3]: *** [/media/hh/pytorch_dir/pytorch/third_party/build/nccl/obj/libwrap.o] Error 1
make[3]: INTERNAL: Exiting with 9 jobserver tokens available; should be 8!
make[2]: *** [lib/libnccl.so] Error 2
make[1]: *** [CMakeFiles/nccl.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'

**Comment by TensorDL** [comment] 2018-06-24 07:58
I am really sorroy for disturbing you again. |I shouldn't ask the question about installation PyTorch from source, but I have no idea to sovle it. Can you help me to fix it out?

System Info：

How you installed PyTorch (conda, pip, source): source
Build command you used (if compiling from source):python setup.py install
OS:ubuntu14.04
PyTorch version:master
Python version: 3.6
CUDA/cuDNN version: cuda8.0+cudnn5.0
GPU models and configuration:GTX1080Ti
GCC version (if compiling from source):4.9.4
CMake version:3.7.2
############################################################
Issue description：

3 errors detected in the compilation of "/tmp/tmpxft_00002a14_00000000-7_THCTensorMath.cpp1.ii".
CMake Error at caffe2_gpu_generated_THCTensorMath.cu.o.Release.cmake:279 (message):
  Error generating file
  /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/pytorch_dir/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCTensorMath.cu.o


make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMath.cu.o] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'

**Comment by zhanghang1989** [comment] 2018-06-24 16:51
Try install the dependencies as following first:
```
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]

# Install basic dependencies
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
conda install -c mingfeima mkldnn

# Add LAPACK support for the GPU
conda install -c pytorch magma-cuda80 # or magma-cuda90 if CUDA 9
```
You may want to ask on PyTorch repo for further help

**Comment by TensorDL** [comment] 2018-06-25 03:00
I have successfully installed the pytorch (0.5.0a0+fc22bf3) and torchvision (0.2.1) from the source. Then I run the test code, i.e., python test.py --dataset PContext --model-zoo Encnet_ResNet50_PContext --eval, in the experiments/segmentation/ folder. After that, the error is occured. 

Issue description：
Traceback (most recent call last):
  File "test.py", line 123, in <module>
    test(args)
  File "test.py", line 40, in test
    transform=input_transform)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/datasets/__init__.py", line 14, in get_segmentation_dataset
    return datasets[name.lower()](**kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/datasets/pcontext.py", line 24, in __init__
    from detail import Detail
ModuleNotFoundError: No module named 'detail'

**Comment by TensorDL** [comment] 2018-06-26 12:20
Are the models you released (model_zoo.py) all trained with SE-loss? 

    models = {
         'encnet_resnet50_pcontext': get_encnet_resnet50_pcontext,
        'encnet_resnet101_pcontext': get_encnet_resnet101_pcontext,
        'encnet_resnet50_ade': get_encnet_resnet50_ade,
        }

**Comment by zhanghang1989** [comment] 2018-06-26 15:16
We only use one Context Encoding Module now, which is more efficient and makes the model compatible with EncNetV2.

**Comment by TensorDL** [comment] 2018-07-01 06:30
Can Ubuntu, Mac and Windows os all run the released codes?

**Comment by zhanghang1989** [comment] 2018-07-01 19:16
It mainly depends on the PyTorch. If the pytorch is compiled successfully on your system, there won't be a problem. I am using both Mac and Ubuntu. Note that PyTorch master branch is required.

**Comment by TensorDL** [comment] 2018-07-03 03:03
The comand (e.g., CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset PContext --model EncNet --aux --se-loss --backbone resnet101)  for training the model means training resnet101 from scratch or finetuning resnet101?

**Comment by zhanghang1989** [comment] 2018-07-03 03:10
resnet101 is pretrained from ImageNet.

**Comment by TensorDL** [comment] 2018-07-03 09:46
I used the comand (CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset PContext --model EncNet --aux --se-loss) for training the model resnet50. However, when it ran the epoch12, I stopped it. Next, I want to restart it, I find unluckily it has ran from epoch0 rather than epoch11. What should I do to run it from epoch11?

**Comment by zhanghang1989** [comment] 2018-07-03 14:50
Please resume by adding command `--resume path/to/checkpoint.pth.tar`

**Comment by zhanghang1989** [comment] 2018-07-06 18:34
This package won't be compatible with PyTroch 0.4.0, but it will be compatible with next stable release.

**Comment by TensorDL** [comment] 2018-07-13 02:32
Question about selayer, why does the selayer have no sigmoid activation function?

(encmodule): EncModule(
      (encoding): Sequential(
        (0): Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
        (3): Encoding(N x 512=>32x512)
        (4): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): ReLU(inplace)
        (6): Mean()
      )
      (fc): Sequential(
        (0): Linear(in_features=512, out_features=512, bias=True)
        (1): Sigmoid()
      )
      (selayer): Linear(in_features=512, out_features=59, bias=True)
    )

**Comment by zhanghang1989** [comment] 2018-07-13 02:35
That is the prediction layer for minimizing SE-Loss. There should be no non-linear layer at the last linear layer.

**Comment by TensorDL** [comment] 2018-08-03 17:22
Sorry for bothering you agian, I have no idea with next error.

/usr/local/anaconda3/bin/python3.6 /media/cv-pc-00/QL_480G/sql/pytorch_dir/PyTorch-Encoding/experiments/segmentation/train.py --dataset PContext --model EncNet --se-loss

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 742, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/cv-pc-00/QL_480G/sql/pytorch_dir/PyTorch-Encoding/experiments/segmentation/train.py", line 17, in <module>
    import encoding.utils as utils
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaledL2, aggregate, pairwise_cosine
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/__init__.py", line 20, in <module>
    ], build_directory=gpu_path, verbose=False)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 496, in load
    with_cuda=with_cuda)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 664, in _jit_compile
    _build_extension_module(name, build_directory)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 748, in _build_extension_module
    name, error.output.decode()))
RuntimeError: Error building extension 'enclib_gpu': [1/4] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/anaconda3/include/python3.6m --compiler-options '-fPIC' -std=c++11 -c /usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
FAILED: roi_align_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/anaconda3/include/python3.6m --compiler-options '-fPIC' -std=c++11 -c /usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu(373): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu(373): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu(420): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu(420): error: class "at::Context" has no member "getCurrentCUDAStream"

4 errors detected in the compilation of "/tmp/tmpxft_0000662c_00000000-7_roi_align_kernel.cpp1.ii".
[2/4] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/anaconda3/include/python3.6m --compiler-options '-fPIC' -std=c++11 -c /usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
FAILED: encoding_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/anaconda3/include/python3.6m --compiler-options '-fPIC' -std=c++11 -c /usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu(315): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu(341): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu(364): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu(391): error: class "at::Context" has no member "getCurrentCUDAStream"

4 errors detected in the compilation of "/tmp/tmpxft_00006623_00000000-7_encoding_kernel.cpp1.ii".
[3/4] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/anaconda3/include/python3.6m --compiler-options '-fPIC' -std=c++11 -c /usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
FAILED: syncbn_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/usr/local/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/local/anaconda3/include/python3.6m --compiler-options '-fPIC' -std=c++11 -c /usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu(183): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu(217): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu(249): error: class "at::Context" has no member "getCurrentCUDAStream"

/usr/local/anaconda3/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu(272): error: class "at::Context" has no member "getCurrentCUDAStream"

4 errors detected in the compilation of "/tmp/tmpxft_00006627_00000000-7_syncbn_kernel.cpp1.ii".
ninja: build stopped: subcommand failed.


Process finished with exit code 1

**Comment by zhanghang1989** [comment] 2018-08-03 17:40
Hi, That is because the PyTorch updates in backend. 

1. Could you change `at::Context:: getCurrentCUDAStream ` to `cudaStream_t stream = at::cuda::getCurrentCUDAStream();`
2. Also add `#include <ATen/cuda/CUDAContext.h>`

This will be fixed in next version.

**Comment by TensorDL** [comment] 2018-08-04 02:11
Thank you for your rely. Can you let me know more in detail? I'm waiting for your reply.

**Comment by TensorDL** [comment] 2018-08-04 08:42
Thank you for your attention. It does work! However, two warnings occurs,  do that matter?

1. /usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1940: 
UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.   warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")

2. /usr/local/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py:1025: 
UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")

**Comment by zhanghang1989** [comment] 2018-08-05 17:52
The deprecate warning is okay for now.

**Comment by TensorDL** [comment] 2018-08-07 03:08
Problem with debug the backward methon of Function class

Hi, aggregate(A, X, C) and scaledL2(X, C, S) in encoding.functions.encoding.py implement the forward and backwark of your custom functions. I want to debug both their forward and backwark,  the pycharm I used has allowed me debug the forward step by step. However, I could not debug backward function like forward. Could you tell me is it possilbe? (ps: for my own  custom functions, I face the same problem)

**Comment by zhanghang1989** [comment] 2018-08-07 17:54
You can directly call the backend function for debugging https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/functions/encoding.py#L77

**Comment by TensorDL** [comment] 2018-08-08 13:40
Do the codes support the machine with a single GPU?

**Comment by zhanghang1989** [comment] 2018-08-08 17:38
CUDA_VISIBLE_DEVICES=0 python train.py ...

**Comment by TensorDL** [comment] 2018-08-09 00:50
I want to debug the program using pycharm-community-2018.1.4. However, I get the error  train.py: error: unrecognized arguments: CUDA_VISIBLE_DEVICES=0

Connected to pydev debugger (build 181.5087.37)
usage: train.py [-h] [--model MODEL] [--backbone BACKBONE] [--dataset DATASET]
                [--data-folder DATA_FOLDER] [--workers N] [--aux] [--se-loss]
                [--epochs N] [--start_epoch N] [--batch-size N]
                [--test-batch-size N] [--lr LR] [--lr-scheduler LR_SCHEDULER]
                [--momentum M] [--weight-decay M] [--no-cuda] [--seed S]
                [--resume RESUME] [--checkname CHECKNAME]
                [--model-zoo MODEL_ZOO] [--ft] [--pre-class PRE_CLASS] [--ema]
                [--eval] [--no-val] [--test-folder TEST_FOLDER]
train.py: error: unrecognized arguments: CUDA_VISIBLE_DEVICES=0

**Comment by zhanghang1989** [comment] 2018-08-09 16:41
Q1: please use the terminal to launch the program.
Q2: That is a kind of standard setting for LR. When increasing the batch size, people typically increase the LR accordingly.
Q3. That is a bug. It will be fixed in next release.

**Comment by TensorDL** [comment] 2018-08-09 17:43
For the question 2 above, due to the limited GPU memory, the batch size has to be small (typically less than 16) unfortunately. It means that  I have to use smaller LR according to the standard setting, i.e., args.lr = lrs[args.dataset.lower()] / 16 * args.batch_size ?

**Comment by zhanghang1989** [comment] 2018-08-09 17:46
Yes. If the batch size is too small, the model will get worse result, because the working batch size for batch normalization is small.

**Comment by TensorDL** [comment] 2018-08-10 09:36
I only have 2 1080 GPU for a total of 16G. The batch size is small less than 16 in experments. Can I alleviate this side effect (the model will get worse result you said) by using larger LR, and set args.lr = lrs[args.dataset.lower()]?

**Comment by zhanghang1989** [comment] 2018-08-10 19:01
The batch size matters for segmentation task, due to working batch size for the Synchronize Batch Normalization. For batch size =16 yields the best performance.

**Comment by TensorDL** [comment] 2018-08-12 12:36
What is the different between encoding.nn.BatchNorm1d and  encoding.nn.BatchNorm2d?

**Comment by zhanghang1989** [comment] 2018-08-13 17:19
same as `torch.nn.BatchNorm1d` and  `torch.nn.BatchNorm2d`

**Comment by TensorDL** [comment] 2018-08-24 03:16
**I have two questions.**
(1) For cos ans poly lr schedules, every batch (iter) has a different lr rather than every batch in one epoch has same lr. Is that right?
(2) For cifar10 recognition, the scaling factor s_k is not learnt but randomly sampling from a uniform distribution between 0 and 1. Is that right?

**Comment by TensorDL** [comment] 2018-09-19 09:04
I'm sorry for disturbing you again, I notice that the scaled_l2 and aggregate opertors within the proposed encoding layer are implemented by C++  language. Duo to I am not good at C++ language, could you share the corresponding implementattion with python code  if you want?

**Comment by zhanghang1989** [comment] 2018-09-19 13:58
We change LR every iter.
The cifar experiment use shake-out like regularization.
Scaled L2 and aggregate are easy to implement in python, but that will be memory consuming.

**Comment by TensorDL** [comment] 2018-09-21 03:00
Sorry to ask the stupid question. The augmented pacal voc 2012 has 11533 images in trainval.txt rather than 10582 used in paper.  It's troubled me. And I do not get the information about how to augment the pacal voc 2012 trainging images to result in 10582 ones.

**Comment by zhanghang1989** [comment] 2018-09-21 17:37
Q1. For VOC experiments, first pretrained on COCO, then finetune on "pascal_aug" and finally on "pascal_voc". I am releasing the training detail for reproducing VOC experiments this weekend.
Q2. Group Norm still has inferior performance comparing to BN. You can easily use that by changing the code a little bit.

**Comment by TensorDL** [comment] 2018-09-24 13:55
I see the training log of EncNet_ResNet50_ADE (https://raw.githubusercontent.com/zhanghang1989/image-data/master/encoding/segmentation/logs/encnet_resnet50_ade.log)

**Comment by zhanghang1989** [comment] 2018-09-24 16:51
There are some bugs in existing code. I am updating them soon.

**Comment by TensorDL** [comment] 2018-09-26 01:17
As mentioned above,  there are some bugs in existing code. I still have a question. The EncNet_ResNet50_ADE achieves 79.9 pixAcc and 41.2 mIoU at the last row in the table  (https://hangzhang.org/PyTorch-Encoding/experiments/segmentation.html), however, I see that it obtains 78.0 pixAc and 40.2 mIoU in the training log file (https://raw.githubusercontent.com/zhanghang1989/image-data/master/encoding/segmentation/logs/encnet_resnet50_ade.log).

**Comment by zhanghang1989** [comment] 2018-09-26 17:12
The validation during the training is using center crop, only for monitoring the training process.

**Closed** 2018-09-26 22:59 UTC
Labels: bug
